import type { HistoricoFuncionalAnalise } from "@/features/historico-funcional/model/historico-funcional.model"
import type { UsuarioConta } from "@/features/usuario/model/usuario.model"

export const DEMO_USUARIO: UsuarioConta = {
  id: 101,
  nome: "Maria Helena Alves",
  apelido: "Mari",
  email: "maria.helena@exemplo.com",
  data_exercicio: "2010-02-15",
  login: "maria.helena",
  senha_cadastrada: true,
  email_confirmado: true,
  criado_em: "2025-01-10T13:20:00.000Z",
  confirmado_em: "2025-01-10T13:25:00.000Z",
}

export const DEMO_HISTORICO: HistoricoFuncionalAnalise = {
  historico_id: 9001,
  usuario_id: DEMO_USUARIO.id,
  arquivo_nome: "historico-funcional-exemplo.pdf",
  nome: DEMO_USUARIO.nome,
  masp: "1234567-8",
  cpf: "123.456.789-00",
  data_emissao: "2025-03-15",
  data_nascimento: "1988-08-12",
  data_posse: "2010-02-01",
  data_exercicio: "2010-02-15",
  cargo_atual: "Analista de Gestão",
  simbolo_atual: "AG-12",
  nivel_atual: "III",
  grau_atual: "B",
  tempo_clt_averbado_anos: 2,
  tempo_clt_creditado_anos: 14,
  data_aposentadoria_por_carreira: "2038-02-01",
  data_aposentadoria_por_idade: "2048-08-12",
  data_aposentadoria_prevista: "2038-02-01",
  dias_trabalhados: 5480,
  dias_totais_ate_aposentadoria: 10950,
  percentual_trabalhado: 50.1,
  percentual_restante: 49.9,
  proxima_progressao_prevista: "2026-09-01",
  proxima_promocao_prevista: "2027-03-01",
  resumo_grafico: {
    tempo_trabalhado_dias: 5480,
    tempo_restante_dias: 5470,
    percentual_trabalhado: 50.1,
    percentual_restante: 49.9,
    eventos_totais: 5,
    eventos_por_status: {
      cumprindo: 2,
      atrasado: 1,
      nao_aplicavel: 1,
      estagio_probatorio: 1,
    },
    eventos_por_tipo: {
      nomeacao: 1,
      progressao: 2,
      promocao: 1,
      substituicao: 1,
    },
  },
  afastamentos_arquivo_nome: "afastamentos-exemplo.pdf",
  afastamentos_resumo: {
    periodos_totais: 2,
    dias_totais: 54,
    dias_por_tipo: {
      aguardando_resultado_conclusivo_de_exame_pericial: 18,
      licenca_para_tratamento_de_saude: 36,
    },
    periodos_por_tipo: {
      aguardando_resultado_conclusivo_de_exame_pericial: 1,
      licenca_para_tratamento_de_saude: 1,
    },
  },
  afastamentos: [
    {
      tipo: "licenca_para_tratamento_de_saude",
      data_inicio: "2024-03-04",
      data_fim: "2024-03-26",
      total_dias: 23,
      legislacao: "Lei 869/1952",
      publicacao: "1952-09-05",
      mes_ano_afastamento: "03/2024",
      dias_restantes_ate_pericia: 0,
    },
    {
      tipo: "aguardando_resultado_conclusivo_de_exame_pericial",
      data_inicio: "2025-06-10",
      data_fim: "2025-06-27",
      total_dias: 18,
      legislacao: "Decreto 48.384/2022",
      publicacao: "2022-11-03",
      mes_ano_afastamento: "06/2025",
      dias_restantes_ate_pericia: 3,
    },
  ],
  eventos: [
    {
      tipo: "nomeacao",
      descricao: "Nomeação inicial para a carreira.",
      cargo: "Analista de Gestão",
      simbolo: "AG-08",
      nivel: "I",
      grau: "A",
      data_publicacao: "2010-02-01",
      data_efetiva: "2010-02-15",
      data_prevista: null,
      status: "nao_aplicavel",
      atraso_dias: 0,
    },
    {
      tipo: "progressao",
      descricao: "Primeira progressão concluída dentro do prazo.",
      cargo: "Analista de Gestão",
      simbolo: "AG-10",
      nivel: "II",
      grau: "A",
      data_publicacao: "2012-07-10",
      data_efetiva: "2012-08-01",
      data_prevista: "2012-08-01",
      status: "cumprindo",
      atraso_dias: 0,
    },
    {
      tipo: "promocao",
      descricao: "Promoção com pequeno atraso administrativo.",
      cargo: "Analista de Gestão",
      simbolo: "AG-11",
      nivel: "II",
      grau: "B",
      data_publicacao: "2015-09-18",
      data_efetiva: "2015-10-06",
      data_prevista: "2015-09-20",
      status: "atrasado",
      atraso_dias: 16,
    },
    {
      tipo: "substituicao",
      descricao: "Atuação temporária em coordenação de equipe.",
      cargo: "Analista de Gestão",
      simbolo: "AG-11",
      nivel: "III",
      grau: "A",
      data_publicacao: "2020-01-06",
      data_efetiva: "2020-02-03",
      data_prevista: null,
      status: "nao_aplicavel",
      atraso_dias: 0,
    },
    {
      tipo: "progressao",
      descricao: "Progressão atual projetada dentro do cronograma.",
      cargo: "Analista de Gestão",
      simbolo: "AG-12",
      nivel: "III",
      grau: "B",
      data_publicacao: "2026-08-15",
      data_efetiva: "2026-09-01",
      data_prevista: "2026-09-01",
      status: "cumprindo",
      atraso_dias: 0,
    },
  ],
  armazenamento_origem: "local",
  processamento_origem: "direto",
}
