[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gestao-carreira"
version = "0.1.0"
description = "Sistema em Python para organizar dados funcionais e de carreira"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Nathália" }]

[project.scripts]
gestao-carreira = "controllers.carreira_controller:executar"

[tool.setuptools.packages.find]
include = ["controllers*", "services*", "schemas*", "models*"]
